### PR TITLE
Upgrade to rustler 0.33.0

### PR DESCRIPTION
**Pull request by almirsarajcic**

### CODE REVIEW

**Comment by praveenperera** [comment]
thanks @almirsarajcic, could you do a PR to my fork of serde_rustler and use that? thanks

**Comment by almirsarajcic** [comment]
@praveenperera, here it is: https://github.com/avencera/serde_rustler/pull/3

**Comment by praveenperera** [comment]
Thanks @almirsarajcic and let’s just point to that repo and master branch

**Comment by praveenperera** [comment]
Thanks @almirsarajcic merged

**Pull request merged**
