### PR TITLE
Support OTP24

### PR DESCRIPTION
**Pull request by gmile**
Update multiple packages to support OTP24. Closes https://github.com/avencera/fast_rss/issues/10.

ℹ️ rustler itself seems to have addressed the issue with OTP24 for some time now, see this thread: https://github.com/rusterlium/rustler/issues/359

### CODE REVIEW

**Comment by bysja** [comment]
Thank you for helping me out with this. 

Your fork does indeed compile, albeit with some warnings:

```
> mix compile
==> earmark_parser
Compiling 1 file (.yrl)
Compiling 2 files (.xrl)
Compiling 3 files (.erl)
Compiling 32 files (.ex)
Generated earmark_parser app
==> nimble_parsec
Compiling 4 files (.ex)
Generated nimble_parsec app
==> makeup
Compiling 44 files (.ex)
Generated makeup app
==> jason
Compiling 10 files (.ex)
Generated jason app
==> makeup_elixir
Compiling 6 files (.ex)
Generated makeup_elixir app
==> makeup_erlang
Compiling 3 files (.ex)
Generated makeup_erlang app
==> ex_doc
Compiling 26 files (.ex)
Generated ex_doc app
==> toml
Compiling 10 files (.ex)
Generated toml app
==> rustler
Compiling 7 files (.ex)
Generated rustler app

The `:rustler` compiler has been deprecated since v0.22.0 and will be
removed in v1.0.

To remove this warning, please consult the CHANGELOG for v0.22.0.

==> fast_rss
Compiling 1 file (.ex)
Compiling crate fastrss in debug mode (native/fastrss)
   Compiling proc-macro2 v1.0.27
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.73
   Compiling serde_derive v1.0.126
   Compiling serde v1.0.126
   Compiling rustler_sys v2.1.1
   Compiling memchr v2.4.0
   Compiling encoding_rs v0.8.28
   Compiling unicode-segmentation v1.7.1
   Compiling void v1.0.2
   Compiling ryu v1.0.5
   Compiling cfg-if v1.0.0
   Compiling rustler v0.22.2
   Compiling lazy_static v1.4.0
   Compiling serde_json v1.0.64
   Compiling itoa v0.4.7
   Compiling quick-error v1.2.3
   Compiling unreachable v1.0.0
   Compiling heck v0.3.3
   Compiling quick-xml v0.20.0
   Compiling quote v1.0.9
   Compiling rustler_codegen v0.22.2
   Compiling rss v1.10.0
   Compiling serde-transcode v1.1.0
   Compiling serde_rustler v0.1.0 (https://github.com/satoren/serde_rustler.git?branch=rustler_0.22#0273c8af)
   Compiling fastrss v0.3.6 ([...]/fast_rss/native/fastrss)
warning: use of deprecated macro `rustler::rustler_export_nifs`: Please use `rustler::init!` instead.
  --> src/lib.rs:12:1
   |
12 | rustler::rustler_export_nifs! {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated macro `::rustler::rustler_export_nifs`: Please use `rustler::init!` instead.
  --> src/lib.rs:12:1
   |
12 | / rustler::rustler_export_nifs! {
13 | |     "Elixir.FastRSS.Native",
14 | |     [
15 | |         ("parse", 1, parse, SchedulerFlags::DirtyCpu),
16 | |     ],
17 | |     None
18 | | }
   | |_^
   |
   = note: this warning originates in the macro `rustler::rustler_export_nifs` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: use of deprecated macro `::rustler::rustler_export_nifs`: Please use `rustler::init!` instead.
  --> src/lib.rs:12:1
   |
12 | / rustler::rustler_export_nifs! {
13 | |     "Elixir.FastRSS.Native",
14 | |     [
15 | |         ("parse", 1, parse, SchedulerFlags::DirtyCpu),
16 | |     ],
17 | |     None
18 | | }
   | |_^
   |
   = note: this warning originates in the macro `$crate::rustler_export_nifs` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: use of deprecated macro `rustler::rustler_atoms`: Please use `atoms!` instead.
 --> src/lib.rs:6:5
  |
6 |     rustler::rustler_atoms! {
  |     ^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated macro `::rustler::rustler_atoms`: Please use `atoms!` instead.
 --> src/lib.rs:6:5
  |
6 | /     rustler::rustler_atoms! {
7 | |         atom ok;
8 | |         atom error;
9 | |     }
  | |_____^
  |
  = note: this warning originates in the macro `rustler::rustler_atoms` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: use of deprecated macro `::rustler::rustler_atoms`: Please use `atoms!` instead.
 --> src/lib.rs:6:5
  |
6 | /     rustler::rustler_atoms! {
7 | |         atom ok;
8 | |         atom error;
9 | |     }
  | |_____^
  |
  = note: this warning originates in the macro `$crate::rustler_atoms` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `fastrss` (lib) generated 9 warnings (3 duplicates)
    Finished dev [unoptimized + debuginfo] target(s) in 8.63s
Generated fast_rss app
```

I managed to get the dependency working this way by vendoring your fork into my Elixir project. I copied the library to `/vendor/fast_rss` in my mix project and added this to `mix.exs`:
```
{:fast_rss, path: "./vendor/fast_rss"}
```

**Comment by praveenperera** [comment]
Oh awesome @gmile, you found a serde_rustler that's been updated for 0.22

**Comment by praveenperera** [comment]
Merged thank @gmile ❤️ 💜 💛 💙

**Comment by gmile** [comment]
@praveenperera awesome, thanks!

**Pull request merged**
